package icons;

import javax.swing.Icon;

import com.intellij.openapi.util.IconLoader;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class DevkitIcons {
	private static Icon load(String path) {
		return IconLoader.getIcon(path, DevkitIcons.class);
	}

	public static final Icon New_html = load("/new_html.png"); // 16x16
}
